### ISSUE TITLE
perf_hooks

### ISSUE THREAD

**Issue by bigfoot31** [CN-Tower/format-to-json#6]
```Can't resolve 'perf_hooks' in '/node_modules/format-to-json'```
node version: v16.16.0

"format-to-json": "^3.0.3"

**Comment by CN-Tower** [comment]
> `Can't resolve 'perf_hooks' in '/node_modules/format-to-json'` node version: v16.16.0
> 
> "format-to-json": "^3.0.3"

Fixed
